// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Fsmb.Api.Ua.Client
{
    using System;
    using System.Collections.Generic;
    using System.Net.Http;
    using System.Threading;
    using System.Threading.Tasks;
    using Microsoft.Rest;
    using Models;

    /// <summary>
    /// Practitioners operations.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "10.0.22.0 (Newtonsoft.Json v11.0.0.0)")]
    public partial interface IPractitioners
    {
        /// <summary>
        /// Gets the submissions for a practitioner.
        /// </summary>
        /// <param name='board'>
        /// Board code
        /// </param>
        /// <param name='fid'>
        /// FID of the practitioner
        /// </param>
        /// <param name='fromDate'>
        /// Optional from date to limit the submissions
        /// </param>
        /// <param name='toDate'>
        /// Optional to date to limit the submissions
        /// </param>
        /// <param name='orderBy'>
        /// </param>
        /// <param name='page'>
        /// </param>
        /// <param name='pageSize'>
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<HttpOperationResponse<IEnumerable<Submission>>> GetByFidWithHttpMessagesAsync(string board, string fid, DateTime? fromDate = default(DateTime?), DateTime? toDate = default(DateTime?), string orderBy = default(string), int? page = default(int?), int? pageSize = default(int?), Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));
        /// <summary>
        /// Gets the current submission for a practitioner.
        /// </summary>
        /// <param name='board'>
        /// Board code
        /// </param>
        /// <param name='fid'>
        /// FID of the practitioner
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<HttpOperationResponse<Submission>> GetLatestWithHttpMessagesAsync(string board, string fid, Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));
        /// <summary>
        /// Gets the submission for a practitioner.
        /// </summary>
        /// <param name='board'>
        /// Board code
        /// </param>
        /// <param name='fid'>
        /// FID of the practitioner
        /// </param>
        /// <param name='id'>
        /// Submission ID
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<HttpOperationResponse<Submission>> GetByIdWithHttpMessagesAsync ( string board, string fid, long id, Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken) );
    }
}
