// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Fsmb.Api.Ua.Client.Models.Addendum
{
    /// <summary>
    /// Accredited training information
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "10.0.22.0 (Newtonsoft.Json v11.0.0.0)")]
    public partial class StateAddendum
    {
        /// <summary>
        /// Date and time the addendum was completed.
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "completedDate", Required = Newtonsoft.Json.Required.Always)]
        public System.DateTime CompletedDate { get; set; }

        /// <summary>
        /// List of questeions and answers.
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "questions", Required = Newtonsoft.Json.Required.Always)]
        public System.Collections.Generic.IList<StateAddendumQuestion> Questions { get; set; }
    }
}
