// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Fsmb.Api.Ua.Client.Models
{

    /// <summary>PDC report</summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "10.0.22.0 (Newtonsoft.Json v11.0.0.0)")]
    public partial class PdcReport
    {
        /// <summary>Date the report was generated</summary>
        [Newtonsoft.Json.JsonProperty("asOfDate", Required = Newtonsoft.Json.Required.Always)]
        public System.DateTime AsOfDate { get; set; }

        /// <summary>Board action status</summary>
        [Newtonsoft.Json.JsonProperty("boardActionStatus", Required = Newtonsoft.Json.Required.Always)]
        public string BoardActionStatus { get; set; }

        /// <summary>Names</summary>
        [Newtonsoft.Json.JsonProperty("names", Required = Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DataAnnotations.Required]
        public PdcNames Names { get; set; }

        /// <summary>Birth date</summary>
        [Newtonsoft.Json.JsonProperty("birthDate", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public PartialDate BirthDate { get; set; }

        /// <summary>Medical education</summary>
        [Newtonsoft.Json.JsonProperty("medicalEducation", Required = Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DataAnnotations.Required]
        public PdcMedicalEducation MedicalEducation { get; set; }

        /// <summary>License information</summary>
        [Newtonsoft.Json.JsonProperty("licenses", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public System.Collections.Generic.IList<PdcLicense> Licenses { get; set; }

        /// <summary>NPI information</summary>
        [Newtonsoft.Json.JsonProperty("npi", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public System.Collections.Generic.IList<PdcNpi> Npi { get; set; }

        /// <summary>ABMS information</summary>
        [Newtonsoft.Json.JsonProperty("abms", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public PdcAbms Abms { get; set; }

        /// <summary>AOA information</summary>
        [Newtonsoft.Json.JsonProperty("aoa", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public PdcAoa Aoa { get; set; }

        /// <summary>DEA information</summary>
        [Newtonsoft.Json.JsonProperty("dea", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public PdcDea Dea { get; set; }
    }
}