// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Fsmb.Api.Ua.Client.Models
{
    /// <summary>
    /// Physician demographic information.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "10.0.22.0 (Newtonsoft.Json v11.0.0.0)")]
    public partial class AmaDemographics
    {
        /// <summary>Legal name prefix.</summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "prefix", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string Prefix { get; set; }

        /// <summary>Legal first name.</summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "firstName", Required = Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = false)]
        public string FirstName { get; set; }

        /// <summary>Legal middle name.</summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "middleName", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string MiddleName { get; set; }

        /// <summary>Legal last name.</summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "lastName", Required = Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = false)]        
        public string LastName { get; set; }

        /// <summary>Legal name suffix.</summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "suffix", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string Suffix { get; set; }

        /// <summary>Date of birth.</summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "birthDate", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public System.DateTime? BirthDate { get; set; }

        /// <summary>Date that physician was confirmed deceased.</summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "deathDate", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public System.DateTime? DeathDate { get; set; }

        /// <summary>Indicates if the profile is for a medical student.</summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "isStudent", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public bool? IsStudent { get; set; }

        /// <summary>Membership status (e.g. 'Member').</summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "amaMembershipStatus", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string AmaMembershipStatus { get; set; }

        /// <summary>Indicates what degree a physician was licensed as ('MD', 'DO').</summary>    
        [Newtonsoft.Json.JsonProperty(PropertyName = "degreeCode", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string DegreeCode { get; set; }
    }
}