// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated. 

namespace Fsmb.Api.Ua.Client.Models
{
    /// <summary>
    /// Medical education.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "10.0.22.0 (Newtonsoft.Json v11.0.0.0)")]
    public partial class AmaMedicalSchool    
    {
        /// <summary>Name of the medical school.</summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "schoolName", Required = Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = false)]
        public string SchoolName { get; set; }

        /// <summary>Type of medical education (Degree or Certificate).</summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "educationType", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string EducationType { get; set; }

        /// <summary>Indicates if a degree was awarded (Yes, No, Enrolled, or 5th Pathway).</summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "degreeAwarded", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string DegreeAwarded { get; set; }

        /// <summary>Graduation year.</summary>    
        [Newtonsoft.Json.JsonProperty(PropertyName = "graduationYear", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string GraduationYear { get; set; }

        /// <summary>Graduation year and optionally month in format 'yyyy-mm'.</summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "graduationDateString", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string GraduationDateString { get; set; }

        /// <summary>Degree code (e.g. 'MD', 'DO').</summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "degreeCode", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string DegreeCode { get; set; }

        /// <summary>Enrollment year and optionally month in format 'yyyy-mm'.</summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "enrollmentDateString", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string EnrollmentDateString { get; set; }
    }
}