// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Fsmb.Api.Ua.Client.Models
{
    /// <summary>
    /// Medical training.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "10.0.22.0 (Newtonsoft.Json v11.0.0.0)")]
    public partial class AmaMedicalTraining
    {
        /// <summary>Name of the program.</summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "programName", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string ProgramName { get; set; }

        /// <summary>Type of training.</summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "trainingType", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string TrainingType { get; set; }

        /// <summary>Name of the institution.</summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "institutionName", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string InstitutionName { get; set; }

        /// <summary>State where the institution is located.</summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "institutionState", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string InstitutionState { get; set; }

        /// <summary>Date physician entered residency training program.</summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "beginDate", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public System.DateTime? BeginDate { get; set; }

        /// <summary>Date physician completed or will complete training program.</summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "endDate", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public System.DateTime? EndDate { get; set; }

        /// <summary>Physician's primary medical specialty based upon accredited graduate medical training program information.</summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "primarySpecialty", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string PrimarySpecialty { get; set; }

        /// <summary>Indicates that current residency training is (Being Verified, Not Yet Verified, Being Reverified or Verified by primary source).</summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "confirmationStatus", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string ConfirmationStatus { get; set; }

        /// <summary>Extra messaging pertaining to this medical training record.</summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "additionalMessage", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string AdditionalMessage { get; set; }
    }
}