// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Fsmb.Api.Ua.Client.Models
{
    /// <summary>
    /// Physician profile.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "10.0.22.0 (Newtonsoft.Json v11.0.0.0)")]
    public partial class AmaReport
    {
        /// <summary>AMA unique ID.</summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "id", Required = Newtonsoft.Json.Required.Always)]
        public long Id { get; set; }

        /// <summary>Date the report was generated.</summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "asOfDate", Required = Newtonsoft.Json.Required.Always)]
        public System.DateTime AsOfDate { get; set; }

        /// <summary>Demographic information.</summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "demographics", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public AmaDemographics Demographics { get; set; }

        /// <summary>Medical education.</summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "medicalSchools", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public System.Collections.Generic.IList<AmaMedicalSchool> MedicalSchools { get; set; }

        /// <summary>Medical training.</summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "medicalTraining", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public System.Collections.Generic.IList<AmaMedicalTraining> MedicalTraining { get; set; }

        /// <summary>NPI information.</summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "npi", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public System.Collections.Generic.IList<AmaNpi> Npi { get; set; }

        /// <summary>Medical licenses.</summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "licenses", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public System.Collections.Generic.IList<AmaLicense> Licenses { get; set; }
    }
}