// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Fsmb.Api.Ua.Client.Models
{
    /// <summary>
    /// Application information
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "10.0.22.0 (Newtonsoft.Json v11.0.0.0)")]
    public partial class Application
    {       
        /// <summary>
        /// Type of license - MD, DO, PA
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "licenseType", Required = Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = false)]
        public string LicenseType { get; set; }

        /// <summary>
        /// Board name
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "boardName", Required = Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = false)]
        public string BoardName { get; set; }

        /// <summary>
        /// Subtype of license
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "licenseSubtypeDetails", Required = Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DataAnnotations.Required]
        public LicenseSubtype LicenseSubtypeDetails { get; set; }
    }
}
