// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Fsmb.Api.Ua.Client.Models
{
    /// <summary>
    /// ECFMG information
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "10.0.22.0 (Newtonsoft.Json v11.0.0.0)")]
    public partial class Ecfmg
    {       
        /// <summary>
        /// ECFMG Number
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "ecfmgNumber", Required = Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = false)]
        public string EcfmgNumber { get; set; }

        /// <summary>
        /// Issue date
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "issueDate", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public System.DateTime? IssueDate { get; set; }
    }
}
