// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Fsmb.Api.Ua.Client.Models
{
    /// <summary>
    /// Exam
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "10.0.22.0 (Newtonsoft.Json v11.0.0.0)")]
    public partial class Exam
    {        
        /// <summary>
        /// Type of exam
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "examType", Required = Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = false)]
        public string ExamType { get; set; }

        /// <summary>
        /// State Code and State Board Description
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "stateBoardDetail", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public ExamStateBoard StateBoardDetail { get; set; }

        /// <summary>
        /// Exam date
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "examDate", Required = Newtonsoft.Json.Required.Always)]
        public System.DateTime ExamDate { get; set; }

        /// <summary>
        /// Number of attempts
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "numberOfAttempts", Required = Newtonsoft.Json.Required.Always, DefaultValueHandling = Newtonsoft.Json.DefaultValueHandling.Populate)]
        public int NumberOfAttempts { get; set; }

        /// <summary>
        /// Pass/fail status (Pass, Fail, Unknown)
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "passFail", Required = Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = false)]
        public string PassFail { get; set; }
    }
}
