// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Fsmb.Api.Ua.Client.Models
{
    /// <summary>
    /// Identity information
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "10.0.22.0 (Newtonsoft.Json v11.0.0.0)")]
    public partial class Identification
    {        
        /// <summary>
        /// SSN
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "ssn", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string Ssn { get; set; }

        /// <summary>
        /// Last 4 of the SSN
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "ssnLast4", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string SsnLast4 { get; set; }

        /// <summary>
        /// NPI
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "npi", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string Npi { get; set; }

        /// <summary>
        /// USMLE ID
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "usmleId", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string UsmleId { get; set; }

        /// <summary>
        /// US citizen indicator
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "isUSCitizen", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string IsUSCitizen { get; set; }

        /// <summary>
        /// Date of birth
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "birthDate", Required = Newtonsoft.Json.Required.Always)]
        public System.DateTime BirthDate { get; set; }

        /// <summary>
        /// City of birth
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "birthCity", Required = Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = false)]
        public string BirthCity { get; set; }

        /// <summary>
        /// State/province of birth
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "birthStateOrProvince", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public Region BirthStateOrProvince { get; set; }

        /// <summary>
        /// Gender
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "gender", Required = Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = false)]
        public string Gender { get; set; }
    }
}
