// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Fsmb.Api.Ua.Client.Models
{
    /// <summary>Entity issuing license</summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "10.0.22.0 (Newtonsoft.Json v11.0.0.0)")]
    public partial class LicenseEntity
    {        
        /// <summary>
        /// Entity code
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "code", Required = Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = false)]
        public string Code { get; set; }

        /// <summary>
        /// Description
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "description", Required = Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = false)]
        public string Description { get; set; }

    }
}
