// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Fsmb.Api.Ua.Client.Models
{
    /// <summary>
    /// License information
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "10.0.22.0 (Newtonsoft.Json v11.0.0.0)")]
    public partial class License
    {        
        /// <summary>
        /// Type of license
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "licenseType", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string LicenseType { get; set; }

        /// <summary>
        /// Entity issuing license
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "licensingEntity", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public LicenseEntity LicensingEntity { get; set; }

        /// <summary>
        /// License status
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "status", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string Status { get; set; }

        /// <summary>
        /// Practitioner type
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "practitionerType", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public PractitionerType PractitionerType { get; set; }

        /// <summary>
        /// License number
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "licenseNumber", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string LicenseNumber { get; set; }

        /// <summary>
        /// Issue date
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "issueDate", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public System.DateTime? IssueDate { get; set; }

        /// <summary>
        /// Expiration date
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "expirationDate", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public System.DateTime? ExpirationDate { get; set; }

    }
}
