// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Fsmb.Api.Ua.Client.Models
{
    /// <summary>
    /// Mailing addresses
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "10.0.22.0 (Newtonsoft.Json v11.0.0.0)")]
    public partial class MailingAddresses
    {        
        /// <summary>
        /// Public address
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "forPublic", Required = Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DataAnnotations.Required]
        public MailingAddress ForPublic { get; set; }

        /// <summary>
        /// Board address
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "forBoard", Required = Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DataAnnotations.Required]
        public MailingAddress ForBoard { get; set; }

        /// <summary>
        /// Other addresses
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "other", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public System.Collections.Generic.IList<MailingAddress> Other { get; set; }
    }
}
