// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Fsmb.Api.Ua.Client.Models
{
    /// <summary>
    /// Mailing address
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "10.0.22.0 (Newtonsoft.Json v11.0.0.0)")]
    public partial class MailingAddress
    {       
        /// <summary>
        /// Type of address (e.g. Business, Home)
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "addressType", Required = Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = false)]
        public string AddressType { get; set; }

        /// <summary>
        /// Address lines
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "lines", Required = Newtonsoft.Json.Required.Always)]        
        [System.ComponentModel.DataAnnotations.Required]
        public System.Collections.Generic.IList<string> Lines { get; set; }

        /// <summary>
        /// City
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "city", Required = Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = false)]
        public string City { get; set; }

        /// <summary>
        /// State/province
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "stateOrProvince", Required = Newtonsoft.Json.Required.Always)]        
        [System.ComponentModel.DataAnnotations.Required]
        public Region StateOrProvince { get; set; }

        /// <summary>
        /// Postal code
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "postalCode", Required = Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = false)]
        public string PostalCode { get; set; }
    }
}
