// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Fsmb.Api.Ua.Client.Models
{
    /// <summary>
    /// Medical education
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "10.0.22.0 (Newtonsoft.Json v11.0.0.0)")]
    public partial class MedicalEducationTraining
    {       
        /// <summary>
        /// Is international graduate?
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "isInternationalGraduate", Required = Newtonsoft.Json.Required.Always)]
        public bool IsInternationalGraduate { get; set; }

        /// <summary>
        /// Graduating school
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "graduating", Required = Newtonsoft.Json.Required.Always)]
        public MedicalEducation Graduating { get; set; }

        /// <summary>
        /// Other medical schools
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "other", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public System.Collections.Generic.IList<MedicalEducation> Other { get; set; }

        /// <summary>
        /// ECFMG information
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "ecfmg", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public Ecfmg Ecfmg { get; set; }

        /// <summary>
        /// 5th Pathway information
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "fifthPathway", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public FifthPathway FifthPathway { get; set; }
    }
}
