// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Fsmb.Api.Ua.Client.Models
{    
    /// <summary>
    /// Medical school education
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "10.0.22.0 (Newtonsoft.Json v11.0.0.0)")]
    public partial class MedicalEducation
    {       
        /// <summary>
        /// Medical school
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "school", Required = Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DataAnnotations.Required]
        public School School { get; set; }

        /// <summary>
        /// Start date
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "beginDate", Required = Newtonsoft.Json.Required.Always)]
        public System.DateTime BeginDate { get; set; }

        /// <summary>
        /// End date
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "endDate", Required = Newtonsoft.Json.Required.Always)]
        public System.DateTime EndDate { get; set; }

        /// <summary>
        /// Degree information
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "degree", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public Degree Degree { get; set; }

        /// <summary>
        /// Graduation date
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "graduationDate", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public System.DateTime? GraduationDate { get; set; }
    }
}
