// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Fsmb.Api.Ua.Client.Models
{
    /// <summary>
    /// Phone information
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "10.0.22.0 (Newtonsoft.Json v11.0.0.0)")]
    public partial class Phones
    {        
        /// <summary>
        /// Public phone
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "forPublic", Required = Newtonsoft.Json.Required.Always)]        
        public Phone ForPublic { get; set; }

        /// <summary>
        /// Board phone
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "forBoard", Required = Newtonsoft.Json.Required.Always)]
        public Phone ForBoard { get; set; }

        /// <summary>
        /// Other phone numbers
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "other", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public System.Collections.Generic.IList<Phone> Other { get; set; }
    }
}
