// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Fsmb.Api.Ua.Client.Models
{    
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "10.0.22.0 (Newtonsoft.Json v11.0.0.0)")]
    public partial class SubmissionRequest
    {       
        /// <summary>
        /// FID to filter (optional if FromDate is set)
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "fid", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string Fid { get; set; }

        /// <summary>
        /// Start date to filter by (optional if Fid is set)
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "fromDate", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public System.DateTime? FromDate { get; set; }

        /// <summary>
        /// End date to filter by (must be &gt;= FromDate)
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "toDate", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public System.DateTime? ToDate { get; set; }

    }
}
