// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Fsmb.Api.Ua.Client.Models
{
    /// <summary>
    /// Summary of a submission
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "10.0.22.0 (Newtonsoft.Json v11.0.0.0)")]
    public partial class SubmissionSummary
    {        
        /// <summary>
        /// Submission ID
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "id", Required = Newtonsoft.Json.Required.Always)]
        public long Id { get; set; }

        /// <summary>
        /// FID of practitioner
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "fid", Required = Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = false)]
        public string Fid { get; set; }

        /// <summary>
        /// Practitioner name
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "name", Required = Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DataAnnotations.Required]
        public Name Name { get; set; }

        /// <summary>
        /// Date/time of submission
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "submitDate", Required = Newtonsoft.Json.Required.Always)]
        public System.DateTime SubmitDate { get; set; }
    }
}
